/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Cell;
import beans.Ground;
import javax.swing.JLabel;

/**
 *
 * @author alle
 */
public class GroundSelector extends javax.swing.JDialog {

  private Cell selected = null;
  private java.awt.Frame parent = null;

  /**
   * Creates new form GroundSelector
   */
  public GroundSelector(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    this.parent = parent;
    initComponents();
    if (((EditorGUI) parent).isSelectorOpen()) {
      super.setLocation(parent.getX() + parent.getWidth() + this.getWidth() + 10, parent.getY());
    } else {
      super.setLocation(parent.getX() + parent.getWidth() + 5, parent.getY());
    }
    this.parent = parent;
    ((EditorGUI) parent).setSelectorOpen(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbW1 = new javax.swing.JLabel();
    lbW5 = new javax.swing.JLabel();
    lbW6 = new javax.swing.JLabel();
    lbW7 = new javax.swing.JLabel();
    lbW2 = new javax.swing.JLabel();
    lbW3 = new javax.swing.JLabel();
    lbW4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(141, 300));
    setPreferredSize(new java.awt.Dimension(141, 300));
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        onClose(evt);
      }
    });
    getContentPane().setLayout(new java.awt.GridLayout(10, 1, 5, 5));

    lbW1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/wiesn/wiesn1nico.png"))); // NOI18N
    lbW1.setText("Wiese 1");
    lbW1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW1);

    lbW5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/wiesn/wiesn2nico.png"))); // NOI18N
    lbW5.setText("Wiese 1 Blumen 1");
    lbW5.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW5);

    lbW6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/wiesn/wiesn3nico.png"))); // NOI18N
    lbW6.setText("Wiese 1 Blumen 2");
    lbW6.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW6);

    lbW7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/wiesn/wiesn4nico.png"))); // NOI18N
    lbW7.setText("Wiese 1 Blumen 3");
    lbW7.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW7);

    lbW2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/Wiesn2.png"))); // NOI18N
    lbW2.setText("Wiese 2");
    lbW2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW2);

    lbW3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/grass.png"))); // NOI18N
    lbW3.setText("Wiese 3");
    lbW3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW3);

    lbW4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lbW4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ground/Green.png"))); // NOI18N
    lbW4.setText("Wiese 4");
    lbW4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(lbW4);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClicked
  {//GEN-HEADEREND:event_onClicked
    selected = new Ground(((JLabel) evt.getSource()).getIcon(), "grass");
    ((EditorGUI) parent).setSelected(selected);
  }//GEN-LAST:event_onClicked

  private void onClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClose

    ((EditorGUI) parent).setSelectorOpen(false);
  }//GEN-LAST:event_onClose

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GroundSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GroundSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GroundSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GroundSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        GroundSelector dialog = new GroundSelector(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lbW1;
  private javax.swing.JLabel lbW2;
  private javax.swing.JLabel lbW3;
  private javax.swing.JLabel lbW4;
  private javax.swing.JLabel lbW5;
  private javax.swing.JLabel lbW6;
  private javax.swing.JLabel lbW7;
  // End of variables declaration//GEN-END:variables
}
