/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Cell;
import beans.Walls;
import javax.swing.JLabel;

/**
 *
 * @author alle
 */
public class WallSelector extends javax.swing.JDialog {

  private Cell selected = null;
  private java.awt.Frame parent = null;

  public WallSelector(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    this.parent = parent;
    initComponents();
    if (((EditorGUI) parent).isSelectorOpen()) {
      super.setLocation(parent.getX() + parent.getWidth() + this.getWidth() + 10, parent.getY());
    } else {
      super.setLocation(parent.getX() + parent.getWidth() + 5, parent.getY());
    }

    ((EditorGUI) parent).setSelectorOpen(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Wall Selector");
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        onClose(evt);
      }
    });
    getContentPane().setLayout(new java.awt.GridLayout(10, 0, 5, 5));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/walls/brick.png"))); // NOI18N
    jLabel1.setText(" Brickwall");
    jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(jLabel1);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/walls/MauerMoos2.png"))); // NOI18N
    jLabel2.setText("Mossy wall");
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        onClicked(evt);
      }
    });
    getContentPane().add(jLabel2);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClicked
  {//GEN-HEADEREND:event_onClicked
    selected = new Walls(((JLabel) evt.getSource()).getIcon(), "wall");
    ((EditorGUI) parent).setSelected(selected);
  }//GEN-LAST:event_onClicked

  private void onClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClose

    ((EditorGUI) parent).setSelectorOpen(false);
  }//GEN-LAST:event_onClose

  public Cell getSelected() {
    return selected;
  }

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(WallSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(WallSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(WallSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(WallSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        WallSelector dialog = new WallSelector(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables
}
